name: Build APK

on:
  push:
    branches:
      - main # Trigger build when there is a push to the main branch
  pull_request:
    branches:
      - main # Trigger build for pull requests targeting the main branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'

      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          api-level: 33
          build-tools: 30.0.3

      - name: Build APK for DTT Staging
        run: ./gradlew :app:assembleDttStagingDebug --stacktrace

      - name: Build APK for Nita Staging
        run: ./gradlew :app:assembleNitaStagingDebug --stacktrace

      - name: Build APK for Production
        run: ./gradlew :app:assembleProductionRelease --stacktrace

      - name: Upload APK Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: built-apks
          path: |
            app/build/outputs/apk/dttStaging/debug/*.apk
            app/build/outputs/apk/nitaStaging/debug/*.apk
            app/build/outputs/apk/production/release/*.apk
