name: Build APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Grant execute permission to gradlew
        run: chmod +x ./gradlew

      - name: Build DTT Staging APK (Debug)
        run: ./gradlew :app:assembleDttStagingDebug --stacktrace

      - name: Build Nita Staging APK (Debug)
        run: ./gradlew :app:assembleNitaStagingDebug --stacktrace

      - name: Build Production APK (Release)
        run: ./gradlew :app:assembleProductionRelease --stacktrace

      - name: Upload APK Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: built-apks
          path: |
            app/build/outputs/apk/dttStaging/debug/*.apk
            app/build/outputs/apk/nitaStaging/debug/*.apk
            app/build/outputs/apk/production/release/*.apk
